name: .NET Core Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout репозиторий
    - name: Checkout repository
      uses: actions/checkout@v3

    # Установка .NET SDK
    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'  # Укажите вашу версию .NET

    # Восстановление зависимостей
    - name: Restore dependencies
      run: dotnet restore

    # Сборка проекта
    - name: Build project
      run: dotnet build --configuration Release

    # Запуск тестов
    - name: Run tests
      run: dotnet test --configuration Release

    # Публикация приложения
    - name: Publish app
      run: dotnet publish --configuration Release --output ./publish

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Checkout репозиторий
      - name: Checkout repository
        uses: actions/checkout@v3

      # Установка .NET SDK
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'  

      # Развертывание на сервере или контейнере
      - name: Deploy app
        run: |
          scp -r ./publish user@server:/path/to/deploy/
